name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 82.197.80.183
        username: u948502898.azeemtvt
        password: ${{ secrets.password }}
